spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF8&autoReconnect=true
  jpa:
    show-sql: true
    open-in-view: false
  redis:
    host: 127.0.0.1
    port: 6379
debug: true